const useAuthTypes = () => {
  const LOGIN = "LOGIN";
  const UPDATE_PROFILE = "UPDATE_PROFILE";
  const LOGOUT = "LOGOUT";
  const REMEMBER = "REMEBER";
  const ISOLD = "ISOLD";
  const DOCUMENTS = "DOCUMENTS";
  const SUGGESTIONSCODES = "SUGGESTIONSCODES";
  const RESETSUGGESTIONSCODES = "RESETSUGGESTIONSCODES";
  const POPUP = "POPUP";
  const SUGGESTIONSBRANDS = "SUGGESTIONSBRANDS";
  const SUGGESTIONSTYPES = "SUGGESTIONSTYPES";

  return {
    LOGIN,
    UPDATE_PROFILE,
    LOGOUT,
    REMEMBER,
    ISOLD,
    DOCUMENTS,
    SUGGESTIONSCODES,
    RESETSUGGESTIONSCODES,
    POPUP,
    SUGGESTIONSBRANDS,
    SUGGESTIONSTYPES,
  };
};
export default useAuthTypes;
