name: Deploy s3 Prod
on:
  push:
    branches: ["main"]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
        - uses: actions/checkout@v3
        - name: Use Node.js 14
          uses: actions/setup-node@v1
          with: 
           node-version: 14
        - name: Install dependencies
          run: npm install

        - name: Build
          run: npm run build

        - name: Deploy
          uses: jakejarvis/s3-sync-action@v0.5.0
          with:
            args: --acl public-read --delete
          env:
            AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.S3_BUCKET_REGION }}
            SOURCE_DIR: 'build'
